services:
  zola-server:
    image: ghcr.io/getzola/zola:v0.19.2
    container_name: "zola"
    build: .
    working_dir: /app
    user: "1000:1000"
    ports:
      - "8080:8080"
    volumes:
      - "$PWD:/app:r"
    restart: always
    command: serve --interface 0.0.0.0 --port 8080 --base-url localhost
